{ pkgs, lib, config, ... }:

{
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.containers."http-echo-echo" = {
    image = "hashicorp/http-echo";
    ports = [
      "5678:5678/tcp"
    ];
    cmd = [ "-text" "Welcome to Citadel" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=echo"
      "--network=http-echo_default"
    ];
  };
  systemd.services."podman-http-echo-echo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-http-echo_default.service"
    ];
    requires = [
      "podman-network-http-echo_default.service"
    ];
    partOf = [
      "podman-compose-http-echo-root.target"
    ];
    wantedBy = [
      "podman-compose-http-echo-root.target"
    ];
  };

  systemd.services."podman-network-http-echo_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f http-echo_default";
    };
    script = ''
      podman network inspect http-echo_default || podman network create http-echo_default
    '';
    partOf = [ "podman-compose-http-echo-root.target" ];
    wantedBy = [ "podman-compose-http-echo-root.target" ];
  };

  systemd.targets."podman-compose-http-echo-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
