{
  pkgs,
  lib,
  config,
  ...
}:

{
  age.secrets.postgres_user.file = ./../../secrets/postgres_user.age;
  age.secrets.postgres_database.file = ./../../secrets/postgres_database.age;
  age.secrets.postgres_password.file = ./../../secrets/postgres_password.age;

  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:18-alpine";
    environmentFiles = [
      config.age.secrets.postgres_user.path
      config.age.secrets.postgres_database.path
      config.age.secrets.postgres_password.path
    ];
    volumes = [
      "postgres_data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=citadel"
    ];
  };
  systemd.services."podman-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-citadel.service"
      "podman-volume-postgres_data.service"
    ];
    requires = [
      "podman-network-citadel.service"
      "podman-volume-postgres_data.service"
    ];
    partOf = [
      "podman-compose-postgres-root.target"
    ];
    wantedBy = [
      "podman-compose-postgres-root.target"
    ];
  };

  systemd.services."podman-network-citadel" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f citadel";
    };
    script = ''
      podman network inspect citadel || podman network create citadel --driver=bridge
    '';
    partOf = [ "podman-compose-postgres-root.target" ];
    wantedBy = [ "podman-compose-postgres-root.target" ];
  };

  systemd.services."podman-volume-postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect postgres_data || podman volume create postgres_data
    '';
    partOf = [ "podman-compose-postgres-root.target" ];
    wantedBy = [ "podman-compose-postgres-root.target" ];
  };

  systemd.targets."podman-compose-postgres-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
