{
  pkgs,
  lib,
  config,
  ...
}:

{
  age.secrets.postgres_user.file = ./../../secrets/postgres_user.age;
  age.secret.postgres_database.file = ./../../secrets/postgres_database.age;
  age.secret.postgres_password.file = ./../../secrets/postgres_password.age;

  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:18-alpine";
    environmentFiles = [
      config.age.secrets.postgres_user.path
      config.age.secrets.postgres_database.path
      config.age.secrets.postgres_password.path
    ];
    volumes = [
      "postgres_data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U postgres"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=postgres_citadel"
    ];
  };
  systemd.services."podman-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-postgres_citadel.service"
      "podman-volume-postgres_postgres_data.service"
    ];
    requires = [
      "podman-network-postgres_citadel.service"
      "podman-volume-postgres_postgres_data.service"
    ];
    partOf = [
      "podman-compose-postgres-root.target"
    ];
    wantedBy = [
      "podman-compose-postgres-root.target"
    ];
  };

  systemd.services."podman-network-postgres_citadel" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f postgres_citadel";
    };
    script = ''
      podman network inspect postgres_citadel || podman network create postgres_citadel --driver=bridge
    '';
    partOf = [ "podman-compose-postgres-root.target" ];
    wantedBy = [ "podman-compose-postgres-root.target" ];
  };

  systemd.services."podman-volume-postgres_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect postgres_postgres_data || podman volume create postgres_postgres_data
    '';
    partOf = [ "podman-compose-postgres-root.target" ];
    wantedBy = [ "podman-compose-postgres-root.target" ];
  };

  systemd.targets."podman-compose-postgres-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
