{ pkgs, lib, ... }:

{
  virtualisation.oci-containers.containers."uptime-kuma" = {
    image = "louislam/uptime-kuma:2";
    environment = {
      "TZ" = "UTC";
      "UMASK" = "0022";
    };
    volumes = [
      "uptime_kuma_data:/app/data:rw"
    ];
    ports = [
      "127.0.0.1:3001:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:3001\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=10s"
      "--health-timeout=5s"
      "--network-alias=uptime-kuma"
      "--network=citadel"
    ];
  };
  systemd.services."podman-uptime-kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-citadel.service"
      "podman-volume-uptime_kuma_data.service"
    ];
    requires = [
      "podman-network-citadel.service"
      "podman-volume-uptime_kuma_data.service"
    ];
    partOf = [
      "podman-compose-uptime-kuma-root.target"
    ];
    wantedBy = [
      "podman-compose-uptime-kuma-root.target"
    ];
  };

  systemd.services."podman-network-citadel" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f citadel";
    };
    script = ''
      podman network inspect citadel || podman network create citadel --driver=bridge
    '';
    partOf = [ "podman-compose-uptime-kuma-root.target" ];
    wantedBy = [ "podman-compose-uptime-kuma-root.target" ];
  };

  systemd.services."podman-volume-uptime_kuma_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect uptime_kuma_data || podman volume create uptime_kuma_data
    '';
    partOf = [ "podman-compose-uptime-kuma-root.target" ];
    wantedBy = [ "podman-compose-uptime-kuma-root.target" ];
  };

  systemd.targets."podman-compose-uptime-kuma-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}